// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjmPyvmT8ZFv05mlzT_M1-kntXu8nskQ',
    appId: '1:705689926965:android:9c8cd8fa043d295ed7e07c',
    messagingSenderId: '705689926965',
    projectId: 'neredeservis-prod-01',
    databaseURL: 'https://neredeservis-prod-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-prod-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zTG0aFscaTVafJq4sLcaAf1IkR1C5H0',
    appId: '1:705689926965:ios:3d3ba8b962fe4a05d7e07c',
    messagingSenderId: '705689926965',
    projectId: 'neredeservis-prod-01',
    databaseURL: 'https://neredeservis-prod-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-prod-01.firebasestorage.app',
    iosBundleId: 'com.neredeservis.app',
  );
}
