// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGX_QJV5dCQVII6k13A3FZ-gUb8GkDTX4',
    appId: '1:691483247415:android:61c42d64a84312938f90b2',
    messagingSenderId: '691483247415',
    projectId: 'neredeservis-stg-01',
    databaseURL: 'https://neredeservis-stg-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-stg-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDI4fAUhDIsclemQNAHQqAV4MfOqs0wvE',
    appId: '1:691483247415:ios:792bc9b1a3b45a718f90b2',
    messagingSenderId: '691483247415',
    projectId: 'neredeservis-stg-01',
    databaseURL: 'https://neredeservis-stg-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-stg-01.firebasestorage.app',
    iosBundleId: 'com.neredeservis.app.stg',
  );
}
