// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4wqXAL1-LP0gtYJ_u7YfMyGwdH98nlw',
    appId: '1:882097896542:android:df71941b8689ead1db88cf',
    messagingSenderId: '882097896542',
    projectId: 'neredeservis-dev-01',
    databaseURL: 'https://neredeservis-dev-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-dev-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqgm9b9n9rGBluTX4wfKnQ_qoniMUJsA',
    appId: '1:882097896542:ios:a729dd50b64a442ddb88cf',
    messagingSenderId: '882097896542',
    projectId: 'neredeservis-dev-01',
    databaseURL: 'https://neredeservis-dev-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'neredeservis-dev-01.firebasestorage.app',
    iosBundleId: 'com.neredeservis.app.dev',
  );
}
