include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    invalid_use_of_protected_member: warning
    todo: ignore

linter:
  rules:
    avoid_print: true
    directives_ordering: true
